### PR TITLE
Tickets/DM-42625: opSim for AOS

### PR DESCRIPTION
**Pull request by suberlak**
First draft of technote describing AOS simulations sourced from opSim database.

### CODE REVIEW

**Review by jbkalmbach — APPROVED** [review]
Reviewed on reviewNB. Looks good, some comments but I think this is great information to keep on hand in a note like this. Thanks!

**Comment by suberlak** [comment]
<p>Included that in the reasoning; updated the text to reflect that.</p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-108/pull/1/discussion/#comment-1909149034'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by suberlak** [comment]
<p>Mentioned the shared AOS repo, and addressed the other issues in the text. </p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-108/pull/1/discussion/#comment-1909149044'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by suberlak** [comment]
<p>It's shown as an example of how it can be done from first principles, so that the know-how doesn't get lost. I'll add a note that in the shared repo these steps have already been performed. </p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-108/pull/1/discussion/#comment-1909149057'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by suberlak** [comment]
<p>Added the OPD vs estimated Zk plot, as well as including the direct detection method. </p>

---

 <a href='https://app.reviewnb.com/lsst-sitcom/sitcomtn-108/pull/1/discussion/#comment-1909149101'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
